name: Discord PR Notifications

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"A new PR has been created: ${{ github.event.pull_request.html_url }}\"}" \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
